const data = [{'path': 'Gallery\\family\\bird.jpg', 'type': 'family'},
{'path': 'Gallery\\family\\lion.jpg', 'type': 'family'},
{'path': 'Gallery\\family\\turtle.jpg', 'type': 'family'},
{'path': 'Gallery\\friends\\beach.jpg', 'type': 'friends'},
{'path': 'Gallery\\friends\\beach2.jpg', 'type': 'friends'},
{'path': 'Gallery\\friends\\beach3.jpeg', 'type': 'friends'},
{'path': 'Gallery\\friends\\desert.jpg', 'type': 'friends'},
{'path': 'Gallery\\greg\\food.jpeg', 'type': 'greg'},
{'path': 'Gallery\\greg\\food2.jpeg', 'type': 'greg'},
{'path': 'Gallery\\greg\\ice-cream.jpg', 'type': 'greg'},
{'path': 'Gallery\\greg\\steak.jpg', 'type': 'greg'}];